In [8]:
import numpy as np
zero=np.zeros((3,4,5))+(5*2)
zero

array([[[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]])

In [22]:
ger=np.linspace(4,8,80, retstep=True)
ger

(array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
        4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
        4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
        4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
        5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
        5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
        5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
        5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
        6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
        6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
        6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
        6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
        7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
        7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
        7.5443038 , 7.59493671, 7.64556962, 7.69

In [35]:
l=[[1,2,3,4,5],[2,2,3,41,2]]
arr=np.asarray(l)
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  2,  3, 41,  2]])

In [52]:
mat=np.matrix(arr)
mat

matrix([[ 1,  2,  3,  4,  5],
        [ 2,  2,  3, 41,  2]])

In [53]:
print(mat.shape)
print(mat.ndim)
print(mat.size)

(2, 5)
2
10


In [49]:
su=arr+mat
su

matrix([[ 2,  4,  6,  8, 10],
        [ 4,  4,  6, 82,  4]])

In [43]:
one=np.ones((2,5,2))
one

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [45]:
print(one.size,sep="")

20
